[window]
decorations = "None"
startup_mode = "Maximized"

[font]
normal = { family = "UbuntuMono Nerd Font Mono" }
size = 9.25
# size = 16

[colors.primary]
background = "#121212"

[env]
TERM="xterm-256color"
