alias vi="nvim"
alias normps="$HOME/bin/normps.sh"
alias prog="git log -- ."
alias cat="bat"
alias ls="ls --color=tty"
alias dc="sudo docker-compose"
alias loadalgo="sudo /home/logan/tech/vpn/load-algo.sh"
alias unloadalgo="sudo /home/logan/tech/vpn/unload-algo.sh"
alias publicip="$HOME/bin/publicip.sh"
