# Don't print a newline at start of the prompt
add_newline = false

# Replace the shell start prompt with $
[character]
symbol = "$"

[memory]
disabled = false
threshold = 80
show_swap = false

[nodejs]
disabled = true

[python]
symbol = "p"
pyenv_version_name = true
disabled = false

